### ISSUE TITLE
Autofire

### ISSUE THREAD

**Issue by paladintodd** [RoxvilleRooster/RoxvilleRooster.github.io#3]
Slight glitch in the autofire macro. As written, it ignores exploding dice. Here is a working version:

Autofire shot 1! [[1d@{Selected|Shooting}! + ?{Modifier|0} -@{Selected|Wounds}[Wounds]  -@{Selected|Fatigue}[Fatigue] ]]  
Autofire shot 2! [[1d@{Selected|Shooting}! + ?{Modifier|0} -@{Selected|Wounds}[Wounds]  -@{Selected|Fatigue}[Fatigue] ]]  
Autofire shot 3! [[1d@{Selected|Shooting}! + ?{Modifier|0} -@{Selected|Wounds}[Wounds]  -@{Selected|Fatigue}[Fatigue] ]]  
Autofire wild die! [[{1d6}kh1 + ?{Modifier|0} -@{Selected|Wounds}[Wounds]  -@{Selected|Fatigue}[Fatigue] ]]

**Comment by RoxvilleRooster** [comment]
Thanks!
So the "kh" is "keep highest" and that is the main source of the error?
I think I need to drop the kh in the wild fire die too, no?

**Comment by paladintodd** [comment]
Correct. Don't need the function there since there is only 1 value.

**Comment by RoxvilleRooster** [comment]
Thanks! I have it now, I think.
This should handle the wild die. I tested and it does explode.

Autofire wild die! [[{1d6!} + ?{Modifier|0} -@{Selected|Wounds}[Wounds]  -@{Selected|Fatigue}[Fatigue] ]]
